/**
 * Generated By Claude Sonnet 4.6
 */

/**
 * WebHID API Type Definitions
 *
 * Covers the interfaces defined in the WebHID specification:
 * https://wicg.github.io/webhid/
 *
 * Includes:
 *   - HIDUnitSystem
 *   - HIDDeviceFilter
 *   - HIDDeviceRequestOptions
 *   - HIDCollectionInfo
 *   - HIDReportInfo
 *   - HIDReportItem
 *   - HIDConnectionEvent / HIDConnectionEventInit
 *   - HIDInputReportEvent / HIDInputReportEventInit
 *   - HIDDevice
 *   - HID
 *   - Navigator / WorkerNavigator extensions
 *
 * @experimental This API is experimental and not yet standardised.
 * @see https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API
 */

// ---------------------------------------------------------------------------
// Enumerations
// ---------------------------------------------------------------------------

/**
 * Identifies the unit system used by a HID report item.
 * @see https://wicg.github.io/webhid/#dom-hidunitsystem
 */
export type HIDUnitSystem =
  | "none"
  | "si-linear"
  | "si-rotation"
  | "english-linear"
  | "english-rotation"
  | "vendor-defined"
  | "reserved";

// ---------------------------------------------------------------------------
// Filter / request option dictionaries
// ---------------------------------------------------------------------------

/**
 * A filter used to narrow the set of HID devices shown in the chooser.
 * All specified fields must match for a device to be included.
 * @see https://wicg.github.io/webhid/#dom-hiddevicefilter
 */
export interface HIDDeviceFilter {
  /** USB vendor identifier (0x0000 – 0xFFFF). */
  vendorId?: number;
  /** USB product identifier (0x0000 – 0xFFFF). */
  productId?: number;
  /** HID usage page number. */
  usagePage?: number;
  /** HID usage number within the given usagePage. */
  usage?: number;
}

/**
 * Options passed to {@link HID.requestDevice}.
 * @see https://wicg.github.io/webhid/#dom-hiddevicerequestoptions
 */
export interface HIDDeviceRequestOptions {
  /**
   * An array of filters.  A device is shown in the chooser if it matches
   * *at least one* filter.  Pass an empty array to show all devices.
   */
  filters: HIDDeviceFilter[];
  /**
   * An optional array of filters used to *exclude* devices.  A device that
   * matches any exclusion filter is removed even when it matched a filter in
   * `filters`.
   */
  exclusionFilters?: HIDDeviceFilter[];
}

// ---------------------------------------------------------------------------
// Report-descriptor data structures
// ---------------------------------------------------------------------------

/**
 * A single item parsed from a HID report descriptor.
 * @see https://wicg.github.io/webhid/#dom-hidreportitem
 */
export interface HIDReportItem {
  /** Whether the item is a constant (true) or data (false). */
  isAbsolute?: boolean;
  /** Whether the data is represented as an array or bitmap. */
  isArray?: boolean;
  /** Whether the buffer format is buffered bytes (true) or bit field (false). */
  isBufferedBytes?: boolean;
  /** Whether the item represents a constant value. */
  isConstant?: boolean;
  /** Whether the usages listed below are linear controls. */
  isLinear?: boolean;
  /** Whether the input has no preferred state to which it returns when the user is not physically interacting with the control. */
  isNonLinear?: boolean;
  /** Whether the control has a preferred state (e.g. a latching push button). */
  isNoPreferred?: boolean;
  /** Whether the null state is a valid output. */
  isNullable?: boolean;
  /** Whether the control emits a fixed-size stream of bytes. */
  isRange?: boolean;
  /** Whether the Usage minimum and maximum define a range of valid usages. */
  isVolatile?: boolean;
  /** Whether the data wraps around past the logical minimum/maximum. */
  isWrap?: boolean;

  /** Array of usage values applicable to this item. */
  usages?: number[];
  /** Inclusive start of a usage range (when `isRange` is true). */
  usageMinimum?: number;
  /** Inclusive end of a usage range (when `isRange` is true). */
  usageMaximum?: number;

  /** Unsigned minimum value reported by the control in its logical coordinate system. */
  reportCount?: number;
  /** Bit size of each data field in the report. */
  reportSize?: number;

  /** Minimum value in the logical coordinate system. */
  logicalMinimum?: number;
  /** Maximum value in the logical coordinate system. */
  logicalMaximum?: number;
  /** Minimum value in the physical coordinate system. */
  physicalMinimum?: number;
  /** Maximum value in the physical coordinate system. */
  physicalMaximum?: number;

  /** Identifies the unit system (e.g. "si-linear"). */
  unitSystem?: HIDUnitSystem;
  /** Magnitude of the units in the lower nibble of the unit value. */
  unitFactorLengthExponent?: number;
  /** Magnitude of the units in the next nibble of the unit value. */
  unitFactorMassExponent?: number;
  unitFactorTimeExponent?: number;
  unitFactorTemperatureExponent?: number;
  unitFactorCurrentExponent?: number;
  unitFactorLuminousIntensityExponent?: number;

  /** Strings that describe this item (from the string descriptor). */
  strings?: string[];
  /** Indices into the device's string descriptors. */
  hasNull?: boolean;
}

/**
 * Describes a single HID report (Input, Output, or Feature).
 * @see https://wicg.github.io/webhid/#dom-hidreportinfo
 */
export interface HIDReportInfo {
  /**
   * A one-byte report identifier.  0 indicates that the device does not
   * use report IDs.
   */
  reportId: number;
  /** Parsed items contained within this report. */
  items: HIDReportItem[];
}

/**
 * Describes a HID collection (top-level or nested) as parsed from the
 * device's report descriptor.
 * @see https://wicg.github.io/webhid/#dom-hidcollectioninfo
 */
export interface HIDCollectionInfo {
  /** HID usage page for this collection. */
  usagePage: number;
  /** HID usage for this collection. */
  usage: number;
  /** Nested collections within this collection. */
  children: HIDCollectionInfo[];
  /** Input reports in this collection. */
  inputReports: HIDReportInfo[];
  /** Output reports in this collection. */
  outputReports: HIDReportInfo[];
  /** Feature reports in this collection. */
  featureReports: HIDReportInfo[];
}

// ---------------------------------------------------------------------------
// HIDConnectionEvent
// ---------------------------------------------------------------------------

/**
 * Init dictionary for {@link HIDConnectionEvent}.
 * @see https://wicg.github.io/webhid/#dom-hidconnectioneventinit
 */
export interface HIDConnectionEventInit extends EventInit {
  /** The device that was connected or disconnected. */
  device: HIDDevice;
}

/**
 * Fired on {@link HID} when a HID device is connected or disconnected.
 *
 * Event types: `"connect"`, `"disconnect"`
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/HIDConnectionEvent
 * @see https://wicg.github.io/webhid/#dom-hidconnectionevent
 */
export interface HIDConnectionEvent extends Event {
  /** The device that triggered this connection event. */
  readonly device: HIDDevice;
}

declare var HIDConnectionEvent: {
  prototype: HIDConnectionEvent;
  new (type: string, eventInitDict: HIDConnectionEventInit): HIDConnectionEvent;
};

// ---------------------------------------------------------------------------
// HIDInputReportEvent
// ---------------------------------------------------------------------------

/**
 * Init dictionary for {@link HIDInputReportEvent}.
 * @see https://wicg.github.io/webhid/#dom-hidinputreporteventinit
 */
export interface HIDInputReportEventInit extends EventInit {
  /** The device that sent the report. */
  device: HIDDevice;
  /**
   * The one-byte report ID prefix, or 0 if the device does not use report
   * IDs.
   */
  reportId: number;
  /** The raw report data (excluding the report ID byte). */
  data: DataView;
}

/**
 * Passed to the `"inputreport"` event handler on {@link HIDDevice} whenever
 * an Input report is received from the device.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/HIDInputReportEvent
 * @see https://wicg.github.io/webhid/#dom-hidinputreportevent
 *
 * @example
 * ```ts
 * device.addEventListener("inputreport", (event: HIDInputReportEvent) => {
 *   const { data, device, reportId } = event;
 *   console.log(device.productName, reportId, data.getUint8(0));
 * });
 * ```
 */
export interface HIDInputReportEvent extends Event {
  /**
   * The raw bytes of the Input report, **excluding** the one-byte report ID
   * prefix (even when the device uses report IDs).
   */
  readonly data: DataView;
  /** The {@link HIDDevice} that sent this report. */
  readonly device: HIDDevice;
  /**
   * The one-byte report ID that prefixes this report, or `0` when the HID
   * interface does not use report IDs.
   */
  readonly reportId: number;
}

declare var HIDInputReportEvent: {
  prototype: HIDInputReportEvent;
  new (
    type: string,
    eventInitDict: HIDInputReportEventInit,
  ): HIDInputReportEvent;
};

// ---------------------------------------------------------------------------
// HIDDevice
// ---------------------------------------------------------------------------

/**
 * Represents a HID interface exposed by a physical device.  A single physical
 * device may be represented by multiple `HIDDevice` instances if it exposes
 * more than one HID interface.
 *
 * Inherits from {@link EventTarget}.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/HIDDevice
 * @see https://wicg.github.io/webhid/#dom-hiddevice
 *
 * @example
 * ```ts
 * const [device] = await navigator.hid.requestDevice({ filters: [] });
 * await device.open();
 *
 * device.addEventListener("inputreport", (e: HIDInputReportEvent) => {
 *   console.log("report", e.reportId, e.data);
 * });
 * ```
 */
export interface HIDDevice extends EventTarget {
  // ---- Events ----

  /**
   * Fired when an Input report is received from the device.
   * The event object is a {@link HIDInputReportEvent}.
   */
  oninputreport: ((this: HIDDevice, ev: HIDInputReportEvent) => unknown) | null;

  // ---- Properties ----

  /** `true` if the connection to the device is currently open. */
  readonly opened: boolean;
  /** The USB vendor ID of the device (0x0000 – 0xFFFF). */
  readonly vendorId: number;
  /** The USB product ID of the device (0x0000 – 0xFFFF). */
  readonly productId: number;
  /** Human-readable product name string provided by the device. */
  readonly productName: string;
  /**
   * The parsed top-level collections from the device's report descriptor.
   * Use these to understand the reports the device supports.
   */
  readonly collections: ReadonlyArray<HIDCollectionInfo>;

  // ---- Methods ----

  /**
   * Opens a connection to the device.
   * Must be called before sending or receiving reports.
   * @returns A Promise that resolves when the connection is established.
   */
  open(): Promise<void>;

  /**
   * Closes the connection to the device.
   * @returns A Promise that resolves when the connection is closed.
   */
  close(): Promise<void>;

  /**
   * Closes the connection and revokes the page's permission to access the
   * device, so that a subsequent call to {@link HID.requestDevice} will be
   * required.
   * @returns A Promise that resolves when access has been revoked.
   */
  forget(): Promise<void>;

  /**
   * Sends an Output report to the device.
   * @param reportId - The one-byte report ID, or `0` if the device does not
   *   use report IDs.
   * @param data - The report payload (must not include the report ID byte).
   * @returns A Promise that resolves when the report has been sent.
   */
  sendReport(reportId: number, data: BufferSource): Promise<void>;

  /**
   * Sends a Feature report to the device.
   * @param reportId - The one-byte report ID, or `0` if the device does not
   *   use report IDs.
   * @param data - The report payload (must not include the report ID byte).
   * @returns A Promise that resolves when the report has been sent.
   */
  sendFeatureReport(reportId: number, data: BufferSource): Promise<void>;

  /**
   * Requests a Feature report from the device.
   * @param reportId - The one-byte report ID, or `0` if the device does not
   *   use report IDs.
   * @returns A Promise that resolves with a {@link DataView} containing the
   *   report data (excluding the report ID byte).
   */
  receiveFeatureReport(reportId: number): Promise<DataView>;

  // ---- Typed event listener overloads ----

  addEventListener(
    type: "inputreport",
    listener: (this: HIDDevice, ev: HIDInputReportEvent) => unknown,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;

  removeEventListener(
    type: "inputreport",
    listener: (this: HIDDevice, ev: HIDInputReportEvent) => unknown,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

declare var HIDDevice: {
  prototype: HIDDevice;
  new (): HIDDevice;
};

// ---------------------------------------------------------------------------
// HID
// ---------------------------------------------------------------------------

/**
 * Entry point for the WebHID API.  Accessible via `navigator.hid` (Window
 * context) or `navigator.hid` inside a Dedicated/Service Worker.
 *
 * Inherits from {@link EventTarget}.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/HID
 * @see https://wicg.github.io/webhid/#dom-hid
 *
 * @example
 * ```ts
 * // Enumerate previously granted devices
 * const devices: HIDDevice[] = await navigator.hid.getDevices();
 *
 * // Request access to a new device
 * const [device] = await navigator.hid.requestDevice({ filters: [] });
 *
 * // Listen for hot-plug events
 * navigator.hid.addEventListener("connect", (e: HIDConnectionEvent) => {
 *   console.log("connected:", e.device.productName);
 * });
 * ```
 */
export interface HID extends EventTarget {
  // ---- Events ----

  /**
   * Fired when a HID device matching a previously granted permission becomes
   * available (e.g. plugged in).
   */
  onconnect: ((this: HID, ev: HIDConnectionEvent) => unknown) | null;

  /**
   * Fired when a previously available HID device is no longer available
   * (e.g. unplugged).
   */
  ondisconnect: ((this: HID, ev: HIDConnectionEvent) => unknown) | null;

  // ---- Methods ----

  /**
   * Returns an array of {@link HIDDevice} objects representing all HID
   * devices that the page already has permission to access.
   *
   * @returns A Promise that resolves with an array of {@link HIDDevice}.
   */
  getDevices(): Promise<HIDDevice[]>;

  /**
   * Prompts the user to select a HID device.  Only callable from a Window
   * context with a user gesture.
   *
   * @param options - Filters controlling which devices appear in the chooser.
   * @returns A Promise that resolves with the array of {@link HIDDevice}
   *   objects selected by the user (may be empty if the user cancels).
   */
  requestDevice(options: HIDDeviceRequestOptions): Promise<HIDDevice[]>;

  // ---- Typed event listener overloads ----

  addEventListener(
    type: "connect",
    listener: (this: HID, ev: HIDConnectionEvent) => unknown,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: "disconnect",
    listener: (this: HID, ev: HIDConnectionEvent) => unknown,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;

  removeEventListener(
    type: "connect",
    listener: (this: HID, ev: HIDConnectionEvent) => unknown,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: "disconnect",
    listener: (this: HID, ev: HIDConnectionEvent) => unknown,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

declare var HID: {
  prototype: HID;
  new (): HID;
};
